name = "MyExample"
uuid = "a2d75f34-f829-4328-92ca-1697c55b5558"
authors = ["wangtianle576"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
